### ISSUE TITLE
"Process not found!" error

### ISSUE THREAD

**Issue by ngbeslhang** [rannmann/SourceCmd#5]
Since I am trying to create a bot for CS:S and since it's in text mode I found SourceCmd and decide to give it a try, but no matter how I type ("hl2", "hl2.exe" etc, both in interactive and command line mode) it just won't detect it even thought I have launched the game long before launching the program (CS:S both in normal and text mode).

I also have tried to restart but to no avail. Since this project is updated 3 years ago I'd like to ask if it's still supported. If no, are there any workaround?

Thank you.

**Comment by rannmann** [comment]
No, I never offered support for this.  But take a look at issue #2 if you're interested further.

Feel free to fork it and take over!

**Comment by ngbeslhang** [comment]
I was first confused when you reference the issue #2 to me but I later changed the code to use the signatures and it worked!

Thanks for helping me. :)
